cacheFolder: ./.cache/yarn

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

packageExtensions:
  '@cspotcode/source-map-support@*':
    dependencies:
      source-map-support: '*'

  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "ts-node":
        optional: true

  "jest@*":
    peerDependencies:
      "ts-node": "*"
    peerDependenciesMeta:
      "ts-node":
        optional: true

  "jest-cli@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "ts-node":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

pnpFallbackMode: none

preferInteractive: true

telemetryInterval: 2

yarnPath: .yarn/releases/yarn-3.2.0.cjs
